name: GitHub Activity Graph

on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate activity graph
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        with:
          github_user_name: ashu6783
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
